#!/usr/bin/env bash
# Bring up an n-seo host on a plain Debian/Ubuntu box.
#
# Works three ways:
#   • as a GCE startup-script (deploy/gcp/setup.sh passes it with
#     --metadata-from-file, and reads engine-repo / mirror-bucket from
#     instance metadata)
#   • run by hand on any VPS or NAS:  sudo ./startup.sh
#   • re-run any time — every step is idempotent
#
# What it does: installs Docker, mounts the data disk if there is one, creates
# the n-seo user, clones (or updates) the engine, prepares the instance
# directory, writes /opt/n-seo/manage, and starts the compose stack.
#
# It deliberately does NOT create your config or run a daily job. The instance
# is yours; `manage init` scaffolds it and you edit it. See README.md.
set -euo pipefail

ENGINE_DIR="${ENGINE_DIR:-/opt/n-seo/engine}"
STATE_DIR="${STATE_DIR:-/srv/n-seo}"
INSTANCE_DIR="${INSTANCE_DIR:-$STATE_DIR/instance}"
RUN_USER="${RUN_USER:-n-seo}"
DATA_DEVICE="${DATA_DEVICE:-/dev/disk/by-id/google-n-seo-data}"

log() { printf '\n[n-seo] %s\n' "$*"; }

meta() {  # read GCE instance metadata; empty elsewhere
  curl -fsS -H 'Metadata-Flavor: Google' --max-time 2 \
    "http://metadata.google.internal/computeMetadata/v1/instance/attributes/$1" 2>/dev/null || true
}

ENGINE_REPO="${ENGINE_REPO:-$(meta engine-repo)}"
ENGINE_REPO="${ENGINE_REPO:-https://github.com/en-dash-consulting/n-seo}"
MIRROR_BUCKET="${MIRROR_BUCKET:-$(meta mirror-bucket)}"

[ "$(id -u)" -eq 0 ] || { echo "run as root (sudo $0)" >&2; exit 1; }

# ------------------------------------------------------------- packages ----
log "packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq ca-certificates curl git

if ! command -v docker >/dev/null 2>&1; then
  log "installing Docker"
  curl -fsSL https://get.docker.com | sh
else
  log "Docker already present ($(docker --version))"
fi
systemctl enable --now docker

# ------------------------------------------------------------ data disk ----
# On GCE the setup script attaches a disk with device-name n-seo-data. On a
# VPS there is usually no second disk and $STATE_DIR is just a directory.
if [ -b "$DATA_DEVICE" ]; then
  if ! blkid "$DATA_DEVICE" >/dev/null 2>&1; then
    log "formatting $DATA_DEVICE (first boot)"
    mkfs.ext4 -m 0 -E lazy_itable_init=0,lazy_journal_init=0,discard "$DATA_DEVICE"
  fi
  mkdir -p "$STATE_DIR"
  if ! mountpoint -q "$STATE_DIR"; then
    log "mounting $DATA_DEVICE at $STATE_DIR"
    mount -o discard,defaults "$DATA_DEVICE" "$STATE_DIR"
  fi
  # Survive reboots. UUID, not device name, so it keeps working if the
  # attachment order changes.
  UUID="$(blkid -s UUID -o value "$DATA_DEVICE")"
  if ! grep -q "$UUID" /etc/fstab; then
    echo "UUID=$UUID $STATE_DIR ext4 discard,defaults,nofail 0 2" >> /etc/fstab
    log "added $STATE_DIR to /etc/fstab"
  fi
else
  log "no data disk at $DATA_DEVICE — using $STATE_DIR on the root filesystem"
  mkdir -p "$STATE_DIR"
fi

# ----------------------------------------------------------------- user ----
if ! id "$RUN_USER" >/dev/null 2>&1; then
  log "creating user $RUN_USER"
  useradd --system --create-home --home-dir "/home/$RUN_USER" --shell /bin/bash "$RUN_USER"
fi
usermod -aG docker "$RUN_USER"
mkdir -p "$INSTANCE_DIR" "$(dirname "$ENGINE_DIR")"
chown -R "$RUN_USER:$RUN_USER" "$STATE_DIR" "$(dirname "$ENGINE_DIR")"

# --------------------------------------------------------------- engine ----
if [ -d "$ENGINE_DIR/.git" ]; then
  log "updating engine"
  sudo -u "$RUN_USER" git -C "$ENGINE_DIR" pull --ff-only || log "pull failed; keeping current checkout"
else
  log "cloning engine from $ENGINE_REPO"
  sudo -u "$RUN_USER" git clone --depth 50 "$ENGINE_REPO" "$ENGINE_DIR"
fi

COMPOSE_FILE="$ENGINE_DIR/docker/compose.yml"
[ -f "$COMPOSE_FILE" ] || { echo "missing $COMPOSE_FILE — is this an n-seo checkout?" >&2; exit 1; }

# ------------------------------------------------- bind the instance dir ----
# compose.yml keeps the instance in a named volume. On a host with a real
# disk we want it at $INSTANCE_DIR instead, so back that volume with a bind
# mount. Overriding the volume definition (rather than the service mounts)
# merges cleanly, because compose appends service volume lists.
OVERRIDE="$STATE_DIR/compose.override.yml"
VOLUMES="$(cd "$ENGINE_DIR" && docker compose -f "$COMPOSE_FILE" config --volumes 2>/dev/null || true)"
VOL_NAME="$(printf '%s\n' "$VOLUMES" | grep -m1 instance || printf '%s\n' "$VOLUMES" | head -1)"
if [ -z "$VOL_NAME" ]; then
  echo "could not determine the instance volume name from $COMPOSE_FILE" >&2
  echo "volumes found: ${VOLUMES:-none}" >&2
  exit 1
fi
log "binding compose volume '$VOL_NAME' to $INSTANCE_DIR"
cat > "$OVERRIDE" <<YAML
# Generated by deploy/vm/startup.sh — puts the instance on this host's disk
# instead of in a Docker-managed volume, so backups and snapshots are simple.
volumes:
  $VOL_NAME:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $INSTANCE_DIR
YAML

ENV_FILE="$STATE_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  cat > "$ENV_FILE" <<ENV
# Host settings for the compose stack. Secrets belong in the instance's own
# .env ($INSTANCE_DIR/.env), not here.
TZ=${TZ:-UTC}
N_SEO_DAILY_AT=07:00
ENV
  log "wrote $ENV_FILE"
fi
chown -R "$RUN_USER:$RUN_USER" "$STATE_DIR"

# --------------------------------------------------------------- manage ----
log "writing /opt/n-seo/manage"
cat > /opt/n-seo/manage <<'MANAGE'
#!/usr/bin/env bash
# Thin wrapper around the compose stack. Run as the n-seo user.
#
#   manage up | down | restart | logs | ps
#   manage init | doctor | daily | demo | export | version   (one-shot)
#   manage upgrade                                           (pull + rebuild)
#   manage shell                                             (a shell in the image)
set -euo pipefail
ENGINE_DIR="${ENGINE_DIR:-/opt/n-seo/engine}"
STATE_DIR="${STATE_DIR:-/srv/n-seo}"
DC=(docker compose --project-name n-seo
    --env-file "$STATE_DIR/.env"
    -f "$ENGINE_DIR/docker/compose.yml"
    -f "$STATE_DIR/compose.override.yml")

# The scheduler service runs `cron`; `compose run` replaces that command, so
# it doubles as the one-shot runner for every other n-seo subcommand.
one_shot() { "${DC[@]}" run --rm scheduler "$@"; }

cmd="${1:-help}"; shift || true
case "$cmd" in
  up)       "${DC[@]}" up -d "$@" ;;
  down)     "${DC[@]}" down "$@" ;;
  restart)  "${DC[@]}" restart "$@" ;;
  logs)     "${DC[@]}" logs -f --tail=200 "$@" ;;
  ps)       "${DC[@]}" ps "$@" ;;
  shell)    "${DC[@]}" run --rm --entrypoint /bin/bash scheduler ;;
  upgrade)
    git -C "$ENGINE_DIR" pull --ff-only
    "${DC[@]}" build --pull
    "${DC[@]}" up -d
    one_shot doctor --offline || true
    ;;
  help|-h|--help)
    sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//' ;;
  *)        one_shot "$cmd" "$@" ;;
esac
MANAGE
chmod 755 /opt/n-seo/manage
chown "$RUN_USER:$RUN_USER" /opt/n-seo/manage

# ------------------------------------------------------------------ boot ----
log "building and starting the stack"
sudo -u "$RUN_USER" /opt/n-seo/manage up || {
  log "compose up failed — check: sudo -u $RUN_USER /opt/n-seo/manage logs"
  exit 1
}

cat <<EOF

[n-seo] host ready.

  engine     $ENGINE_DIR
  instance   $INSTANCE_DIR   $( [ -f "$INSTANCE_DIR/n-seo.config.json" ] && echo "(configured)" || echo "(NOT configured yet)" )
  manage     /opt/n-seo/manage
  mirror     ${MIRROR_BUCKET:-(none configured)}

Next, as the n-seo user:

  sudo -u $RUN_USER /opt/n-seo/manage init      # scaffold the instance
  sudo -u $RUN_USER vi $INSTANCE_DIR/n-seo.config.json
  sudo -u $RUN_USER /opt/n-seo/manage doctor

The dashboard listens inside the container only. Do not publish its port.
Tunnel to it (IAP, SSH -L or Tailscale) — see deploy/vm/README.md.
EOF
